logging:
  config: classpath:logback-dev.xml
swagger:
  enabled: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/adam?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;&useSSL=false
    username: root
    password: root
  redis:
    database: 0
    redis: localhost
    port: 6379


